<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Zend Framework Tutorial</title>
  <?php echo $this->headLink()->appendStylesheet('//twitter.github.com/bootstrap/assets/css/bootstrap.css') . PHP_EOL; ?>
  <?php echo $this->headScript()->appendFile('//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js') . PHP_EOL; ?>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="span12">
        <p>This is the header!</p>
      </div>
    </div>
    <div class="row">
      <div class="span12">